{\rtf1\ansi\ansicpg1252\cocoartf2821
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Times-Roman;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww28600\viewh15140\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 name: Create Dummy Repositories\
\
on:\
  workflow_dispatch:  # Allows manual trigger\
\
jobs:\
  create_repos:\
    runs-on: ubuntu-latest\
\
    steps:\
      - name: Checkout Repository\
        uses: actions/checkout@v3\
\
      - name: Create 50 Dummy Repositories\
        env:\
          GH_TOKEN: $\{\{ secrets.GH_TOKEN \}\}\
          ORG_NAME: "lalitsudhakar"  # Change if using an organization\
        run: |\
          for i in $(seq 1 50); do\
            REPO_NAME="dummy-repo-$i"\
            echo "Creating repository: $REPO_NAME"\
\
            curl -X POST -H "Authorization: token $GH_TOKEN" \\\
              -H "Accept: application/vnd.github.v3+json" \\\
              https://api.github.com/user/repos \\\
              -d '\{"name":"'"$REPO_NAME"'", "private":false\}'\
\
            sleep 2  # Prevent rate limiting\
          done\
}
