name: Create Dummy Repos

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  create_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create 50 Dummy Repositories
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ORG_NAME: "your-github-username"  # Change to your GitHub username or org
        run: |
          for i in $(seq 1 50); do
            REPO_NAME="dummy-repo-$i"
            echo "Creating repository: $REPO_NAME"

            # Create a private repository
            curl -s -X POST -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/orgs/$ORG_NAME/repos \
              -d "{\"name\": \"$REPO_NAME\", \"private\": true}" > /dev/null

            # Clone, create branches, and push sample code
            git clone "https://$GH_TOKEN@github.com/$ORG_NAME/$REPO_NAME.git"
            cd $REPO_NAME

            for BRANCH in "Test-Github" "Docker-Dev" "Prod" "Stage"; do
              git checkout --orphan $BRANCH
              echo "print('Hello from $BRANCH branch')" > sample.py
              git add sample.py
              git commit -m "Added sample code to $BRANCH"
              git push origin $BRANCH
            done

            cd ..
            rm -rf $REPO_NAME  # Cleanup
          done
