name: Create Dummy Repository

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  create_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Git Config
        run: |
          git config --global user.email "lalittanysudhakar@gmail.com"
          git config --global user.name "lalitsudhakar"

      - name: Delete existing repo (if exists)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ORG_NAME: "lalitsudhakar"
          REPO_NAME: "dummy-repo"
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$ORG_NAME/$REPO_NAME)

          if [[ "$response" == "204" ]]; then
            echo "Existing repository deleted successfully."
          else
            echo "No existing repository found or failed to delete."
          fi
          sleep 2

      - name: Create a new repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ORG_NAME: "lalitsudhakar"
          REPO_NAME: "dummy-repo"
        run: |
          curl -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/repos \
            -d '{"name": "'"$REPO_NAME"'", "private": false}'
          sleep 2

      - name: Initialize repository and add branches
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ORG_NAME: "lalitsudhakar"
          REPO_NAME: "dummy-repo"
        run: |
          git clone https://$GH_TOKEN@github.com/$ORG_NAME/$REPO_NAME.git
          cd $REPO_NAME

          echo 'print("Hello from Dummy Repo")' > main.py
          git add main.py
          git commit -m "Add dummy Python script"
          git push origin main

          for branch in "Test-Github" "Docker-Dev" "Prod" "Stage"; do
            git checkout -b $branch
            git push origin $branch
          done
